name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -ex
            cd /home/ubuntu/moodCookbook
            git reset --hard
            git clean -fd
            git pull https://${{ secrets.GIT_HUB_USER_DEPLOY }}:${{ secrets.GIT_HUB_TOKEN_DEPLOY }}@github.com/NxSYED-ux/moodCookbook.git main

            # Create fresh .env
            cat > .env <<EOL
NODE_ENV=production
PORT=${{ secrets.PORT }}
GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
DB_URI=${{ secrets.DB_URI }}
JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOL
  
          # Install backend dependencies
          npm install || true
          
          # Build frontend
          if [ -d client ]; then
          cd client
          npm install
          npm run build
          cd ..
          fi
          
          # Restart backend with updated environment
          pm2 restart backend --update-env || pm2 start /home/ubuntu/moodCookbook/index.js --name backend --update-env
          
          # Reload Nginx
          sudo systemctl reload nginx
