uses: appleboy/ssh-action@v0.1.6
with:
  host: ${{ secrets.EC2_HOST }}
  username: ${{ secrets.EC2_USER }}
  key: ${{ secrets.EC2_KEY }}
  script: |
    set -e   # exit on first error
    cd /home/ubuntu/moodCookbook
    echo "Resetting repo..."
    git reset --hard
    git clean -fd
    echo "Pulling latest code..."
    git pull origin main
    echo "Installing backend..."
    npm install
    echo "Building frontend..."
    cd /home/ubuntu/moodCookbook/dist/spa || exit 1
    npm install || true
    npm run build
    echo "Restarting PM2 backend..."
    pm2 restart backend || pm2 start server.js --name backend
    echo "Reloading Nginx..."
    sudo systemctl reload nginx
    echo "Deployment complete!"
