name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo on GitHub runner (needed for github.repository info)
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Deploy to EC2 via SSH
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -ex
            cd /home/ubuntu/moodCookbook
            git reset --hard
            git clean -fd
            git pull https://${{ secrets.GIT_HUB_USER_DEPLOY }}:${{ secrets.GIT_HUB_TOKEN_DEPLOY }}@github.com/NxSYED-ux/moodCookbook.git main
            /usr/bin/npm install
            cd /home/ubuntu/moodCookbook/dist/spa || exit 1
            /usr/bin/npm install || true
            /usr/bin/npm run build
            /usr/bin/pm2 restart backend || /usr/bin/pm2 start /home/ubuntu/moodCookbook/server.js --name backend
            sudo systemctl reload nginx